# Generated by Django 5.0.2 on 2024-03-10 12:47

import CarZone.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carzoneuser',
            name='location',
            field=models.CharField(choices=[('Burgas', 'Burgas'), ('Dobrich', 'Dobrich'), ('Pleven', 'Pleven'), ('Plovdiv', 'Plovdiv'), ('Razgrad', 'Razgrad'), ('Ruse', 'Ruse'), ('Sliven', 'Sliven'), ('Sofia', 'Sofia'), ('Targovishte', 'Targovishte'), ('Varna', 'Varna'), ('Veliko Tarnovo', 'Veliko Tarnovo'), ('Vidin', 'Vidin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='carzoneuser',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[CarZone.accounts.validators.validate_phone_number]),
        ),
    ]
