# Generated by Django 5.0.2 on 2024-03-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_carzoneuser_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carzoneuser',
            name='location',
            field=models.CharField(choices=[('', '-----'), ('Sofia', 'Sofia'), ('Plovdiv', 'Plovdiv'), ('Varna', 'Varna'), ('Burgas', 'Burgas'), ('Ruse', 'Ruse'), ('Sliven', 'Sliven'), ('Veliko Tarnovo', 'Veliko Tarnovo'), ('Pleven', 'Pleven'), ('Razgrad', 'Razgrad'), ('Targovishte', 'Targovishte'), ('Dobrich', 'Dobrich'), ('Vidin', 'Vidin')], max_length=20),
        ),
    ]
