# Generated by Django 5.0.2 on 2024-03-15 15:10

import CarZone.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_carzoneuser_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carzoneuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[CarZone.accounts.validators.validate_phone_number]),
        ),
    ]
