# Generated by Django 5.0.2 on 2024-03-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_carzoneuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carzoneuser',
            name='location',
            field=models.CharField(blank=True, choices=[('', '-----'), ('Sofia', 'Sofia'), ('Plovdiv', 'Plovdiv'), ('Varna', 'Varna'), ('Burgas', 'Burgas'), ('Ruse', 'Ruse'), ('Sliven', 'Sliven'), ('Veliko Tarnovo', 'Veliko Tarnovo'), ('Stara Zagora', 'Stara Zagora'), ('Pleven', 'Pleven'), ('Razgrad', 'Razgrad'), ('Targovishte', 'Targovishte'), ('Dobrich', 'Dobrich'), ('Vidin', 'Vidin')], max_length=20, null=True),
        ),
    ]
