# Generated by Django 5.0.2 on 2024-03-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='views',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
