# Generated by Django 5.0.2 on 2024-03-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_car_dealer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='features',
            field=models.ManyToManyField(blank=True, null=True, to='car.feature'),
        ),
    ]
