# Generated by Django 5.0.2 on 2024-03-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_alter_car_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Wagon', 'Wagon'), ('Hatchback', 'Hatchback'), ('SUV', 'SUV'), ('', '')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=models.ManyToManyField(to='car.feature'),
        ),
    ]
