# Generated by Django 5.0.2 on 2024-03-12 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_alter_car_body_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('White', 'White'), ('Grey', 'Grey'), ('Black', 'Black'), ('Red', 'Red'), ('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Green', 'Green')], default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='car',
            name='euro_standard',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Bensine', 'Bensine'), ('Diesel', 'Diesel'), ('Gas', 'Gas'), ('Electric', 'Electric')], default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(750000)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission_type',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='car',
            name='warranty',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
