# Generated by Django 5.0.2 on 2024-03-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_alter_car_color_alter_car_euro_standard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='euro_standard',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('', 'Select a value'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=None, null=True),
        ),
    ]
