# Generated by Django 5.0.2 on 2024-03-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_alter_car_euro_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('White', 'White'), ('Grey', 'Grey'), ('Black', 'Black'), ('Red', 'Red'), ('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Green', 'Green'), ('Select a color', 'Default')], default='Select a color', max_length=15),
        ),
        migrations.AlterField(
            model_name='car',
            name='euro_standard',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('', 'Select euro standard'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True),
        ),
    ]
