# Generated by Django 5.0.2 on 2024-03-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_alter_car_body_type_alter_car_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('', 'Select body type'), ('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Wagon', 'Wagon'), ('Hatchback', 'Hatchback'), ('SUV', 'SUV'), ('Limousine', 'Limousine'), ('Pickup', 'Pickup'), ('Van', 'Van')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='euro_standard',
            field=models.PositiveSmallIntegerField(choices=[('', 'Select euro standard'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('', 'Select fuel type'), ('Bensine', 'Bensine'), ('Diesel', 'Diesel'), ('Gas', 'Gas'), ('Electric', 'Electric')], max_length=15),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission_type',
            field=models.CharField(choices=[('', 'Select transmission type'), ('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=15),
        ),
    ]
