# Generated by Django 5.0.2 on 2024-03-12 14:22

import CarZone.car.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_alter_car_body_type_alter_car_euro_standard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_available',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='manufacture_year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), CarZone.car.validators.validate_manufacture_year]),
        ),
    ]
