# Generated by Django 5.0.2 on 2024-03-12 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0013_car_is_available_alter_car_manufacture_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='capacity',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(7500)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='horsepower',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
