# Generated by Django 5.0.2 on 2024-03-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0014_alter_car_capacity_alter_car_horsepower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('', '-----'), ('Sedan', 'Sedan'), ('Limousine', 'Limousine'), ('Coupe', 'Coupe'), ('Cabrio', 'Cabrio'), ('Wagon', 'Wagon'), ('Hatchback', 'Hatchback'), ('SUV', 'SUV'), ('Pickup', 'Pickup'), ('Van', 'Van')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('', '-----'), ('White', 'White'), ('Grey', 'Grey'), ('Black', 'Black'), ('Red', 'Red'), ('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Green', 'Green')], max_length=15),
        ),
        migrations.AlterField(
            model_name='car',
            name='euro_standard',
            field=models.PositiveSmallIntegerField(choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('', '-----'), ('Bensine', 'Bensine'), ('Diesel', 'Diesel'), ('Gas', 'Gas'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=15),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission_type',
            field=models.CharField(choices=[('', '-----'), ('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=15),
        ),
    ]
