# Generated by Django 5.0.2 on 2024-03-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0015_alter_car_body_type_alter_car_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
