# Generated by Django 5.0.2 on 2024-03-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0016_manufacturer_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='nationality',
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='country',
            field=models.CharField(blank=True, choices=[('England', 'England'), ('Germany', 'Germany'), ('France', 'France'), ('Spain', 'Spain'), ('Italy', 'Italy'), ('Sweden', 'Sweden'), ('Denmark', 'Denmark'), ('Czechia', 'Czechia'), ('Austria', 'Austria'), ('China', 'China'), ('South Korea', 'South Korea'), ('Japan', 'Japan')], max_length=50, null=True),
        ),
    ]
