# Generated by Django 5.0.2 on 2024-03-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0018_car_posted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('', '-----'), ('White', 'White'), ('Grey', 'Grey'), ('Black', 'Black'), ('Red', 'Red'), ('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Green', 'Green'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Brown', 'Brown')], max_length=15),
        ),
    ]
